/**
 * Server-only helper that builds a tiny one-page "sample" envelope so
 * operators can grab a working /sign link for manual QA without uploading
 * a real document. The envelope is auto-sent and the helper returns the
 * signing URL for the lone Sample Signer recipient.
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { createEnvelopeServer, addDocumentServer } from "./envelopes.server";
import { upsertRecipientsServer } from "./recipients.server";
import { upsertFieldServer } from "./fields.server";
import { sendEnvelopeServer } from "./send.server";
import { mintRecipientSigningLink } from "./links.server";

async function buildSamplePdfBytes(title: string): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]); // US Letter, pt
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("BusAcTa Operations — Sample document", {
    x: 60,
    y: 720,
    size: 18,
    font: bold,
    color: rgb(0.1, 0.1, 0.15),
  });
  page.drawText(title, {
    x: 60,
    y: 695,
    size: 11,
    font,
    color: rgb(0.3, 0.3, 0.35),
  });
  page.drawText("This is a generated test document. Please sign in the box below.", {
    x: 60,
    y: 640,
    size: 12,
    font,
    color: rgb(0.15, 0.15, 0.2),
  });

  // Signature target box (visual cue only — the real field is positioned
  // below with esign_fields coords).
  page.drawRectangle({
    x: 60,
    y: 120,
    width: 260,
    height: 70,
    borderColor: rgb(0.6, 0.6, 0.7),
    borderWidth: 1,
  });
  page.drawText("Signature", {
    x: 64,
    y: 100,
    size: 9,
    font,
    color: rgb(0.45, 0.45, 0.5),
  });

  return pdf.save();
}

export async function createSampleEnvelopeServer(opts: {
  user_id: string;
  firm_id: string;
  origin: string;
}): Promise<{ envelope_id: string; signing_url: string | null }> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const title = `Sample envelope — ${stamp}`;

  // 1. Envelope
  const envelopeId = await createEnvelopeServer({
    firm_id: opts.firm_id,
    title,
    project_id: null,
    message: "This is a test envelope generated by the E-Sign sample tool.",
    routing_mode: "sequential",
    expires_in_days: 30,
    reminder_cadence_hours: 48,
    created_by: opts.user_id,
  });

  // 2. PDF → storage → document row
  const bytes = await buildSamplePdfBytes(title);
  const path = `${envelopeId}/${crypto.randomUUID()}.pdf`;
  const { error: upErr } = await supabaseAdmin.storage
    .from("esign-source")
    .upload(path, bytes, { contentType: "application/pdf", upsert: false });
  if (upErr) throw new Error(`Sample PDF upload failed: ${upErr.message}`);
  const documentId = await addDocumentServer({
    envelope_id: envelopeId,
    name: "Sample document.pdf",
    source_mime: "application/pdf",
    source_path: path,
    order_index: 0,
  });

  // 3. Single signer
  const { ids } = await upsertRecipientsServer(envelopeId, [
    {
      full_name: "Sample Signer",
      email: "sample-signer@example.com",
      role: "signer",
      auth_method: "email_link",
      routing_order: 1,
    },
  ]);
  const recipientId = ids[0];
  if (!recipientId) throw new Error("Sample recipient was not created");

  // 4. One signature field on page 1 (pdf-lib origin = bottom-left, in pt)
  await upsertFieldServer({
    envelope_id: envelopeId,
    document_id: documentId,
    recipient_id: recipientId,
    field_type: "signature",
    page_index: 0,
    x_pt: 60,
    y_pt: 120,
    width_pt: 260,
    height_pt: 70,
    is_required: true,
  });

  // 5. Send the envelope (transitions draft → sent and emits links)
  const result = await sendEnvelopeServer(envelopeId, opts.origin);
  let url: string | null = null;
  if (result.ok) {
    const link = result.links.find((l) => l.recipient_id === recipientId);
    url = link?.url ?? null;
  } else {
    // Fall back to minting a link directly so the operator still gets a URL.
    try {
      const minted = await mintRecipientSigningLink(envelopeId, recipientId, opts.origin);
      url = minted.url;
    } catch {
      url = null;
    }
  }

  return { envelope_id: envelopeId, signing_url: url };
}

export async function pickFirmForUserServer(_userId: string): Promise<string | null> {
  // Fall back to any firm with the smallest identifier so demo accounts
  // always resolve. user_roles does not carry firm scope in this schema.
  const { data: anyFirm } = await supabaseAdmin
    .from("firms")
    .select("id")
    .order("firm_identifier", { ascending: true })
    .limit(1);
  return (anyFirm ?? [])[0]?.id ?? null;
}
