/**
 * Server-only helpers for the B2C Client hub.
 * Imported only by *.functions.ts modules.
 */
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolvePasswordResetUrl } from "@/lib/shared/request-origin.server";

export interface CreateDirectClientArgs {
  display_name: string;
  legal_name?: string | null;
  email: string;
  phone?: string | null;
  client_type: "individual" | "business";
  identifier?: string | null;
  task_type_id?: string | null;
  organizer_template_id?: string | null;
  created_by: string;
}

export async function createDirectClientServer(args: CreateDirectClientArgs) {
  const admin = supabaseAdmin;
  const email = args.email.trim().toLowerCase();

  // 0. Provision a portal auth user + profile so this client shows up in
  //    Admin Center → Members alongside Firm Hub / HR Hub provenances.
  let portalUserId: string | null = null;
  const created = await admin.auth.admin.createUser({
    email,
    password: crypto.randomUUID() + "Aa1!",
    email_confirm: true,
    user_metadata: { full_name: args.display_name, portal: true },
  });
  if (created.error) {
    if (!/already|exists|registered/i.test(created.error.message)) {
      console.error("[direct-clients] createUser failed:", created.error);
      throw new Error(`Portal user creation failed: ${created.error.message}`);
    }
    const list = await admin.auth.admin.listUsers({ page: 1, perPage: 200 });
    if (list.error) throw list.error;
    const existing = list.data.users.find((u) => (u.email || "").toLowerCase() === email);
    portalUserId = existing?.id ?? null;
  } else {
    portalUserId = created.data.user?.id ?? null;
  }
  if (!portalUserId) throw new Error("Failed to resolve portal user id");

  const { error: profileErr } = await admin.from("profiles").upsert(
    {
      id: portalUserId,
      email,
      full_name: args.display_name,
      phone: args.phone ?? null,
      provisioned_via: "direct_client_hub",
      portal_enabled: true,
      status: "active",
    } as never,
    { onConflict: "id" },
  );
  if (profileErr) {
    console.error("[direct-clients] profile upsert failed:", profileErr);
    throw new Error(`Profile sync failed: ${profileErr.message}`);
  }

  const { error: roleErr } = await admin
    .from("user_roles")
    .upsert({ user_id: portalUserId, role: "client" as never }, { onConflict: "user_id,role" });
  if (roleErr) {
    console.error("[direct-clients] role upsert failed:", roleErr);
    throw new Error(`Role sync failed: ${roleErr.message}`);
  }

  try {
    await admin.auth.admin.generateLink({
      type: "recovery",
      email,
      options: { redirectTo: resolvePasswordResetUrl() },
    });
  } catch (e) {
    console.warn("[direct-clients] recovery link failed (non-fatal):", e);
  }

  // 1. Create the B2C client row.
  const { data: client, error: clientErr } = await admin
    .from("direct_clients")
    .insert({
      display_name: args.display_name,
      legal_name: args.legal_name ?? null,
      email,
      phone: args.phone ?? null,
      client_type: args.client_type,
      identifier: args.identifier ?? null,
      provisioned_via: "direct_client_hub",
      created_by: args.created_by,
      owner_id: args.created_by,
      portal_user_id: portalUserId,
      // client_code is auto-generated by trg_direct_clients_assign_code; "" lets the trigger replace it
      client_code: "",
    })
    .select("*")
    .single();
  if (clientErr) throw new Error(clientErr.message);

  let deploymentId: string | null = null;

  // 2. Dispatch organizer if a template was selected.
  if (args.organizer_template_id) {
    const { data: tpl, error: tplErr } = await supabaseAdmin
      .from("organizer_templates")
      .select("id,version")
      .eq("id", args.organizer_template_id)
      .maybeSingle();
    if (tplErr) throw new Error(tplErr.message);

    const { data: dep, error: depErr } = await supabaseAdmin
      .from("organizer_deployments")
      .insert({
        template_id: args.organizer_template_id,
        template_version: tpl?.version ?? 1,
        target_type: "direct_client",
        target_id: client.id,
        assigned_by: args.created_by,
        external_name: client.display_name,
        external_email: client.email,
        status: "not_started",
        assignee_profile_id: portalUserId,
      })
      .select("id")
      .single();
    if (depErr) throw new Error(depErr.message);
    deploymentId = dep.id;
  }

  // 3. Create the placeholder task for this engagement — only when an
  //    engagement (task type) was supplied. B2C client onboarding no longer
  //    captures an engagement, so this is skipped for those clients.
  let taskId: string | null = null;
  if (args.task_type_id) {
    const { data: task, error: taskErr } = await supabaseAdmin
      .from("tasks")
      .insert({
        title: args.display_name,
        direct_client_id: client.id,
        task_type_id: args.task_type_id,
        stream: "direct",
        status: "draft",
        created_by: args.created_by,
        source_organizer_deployment_id: deploymentId,
      })
      .select("id")
      .single();
    if (taskErr) throw new Error(taskErr.message);
    taskId = task.id;
  }

  return { client, deploymentId, taskId };
}
