/**
 * URL slug helpers.
 *
 * The database is the source of truth for slugs (generated by a BEFORE INSERT
 * trigger — see migration `20260603800000_readable_slugs.sql`). These helpers
 * mirror that logic for client-side previews and tests; they must stay in sync
 * with the Postgres `slugify()` function.
 */

/** kebab-case, ascii, trimmed, length-capped (mirror of Postgres `slugify()`). */
export function slugify(input: string): string {
  return (input ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/^-+|-+$/g, "");
}

/**
 * Returns `base`, or `base-2`, `base-3`… for the first value not already in
 * `existing`. Used when previewing a slug before the row is inserted.
 */
export function dedupeSlug(base: string, existing: Set<string>): string {
  if (!existing.has(base)) return base;
  let n = 2;
  while (existing.has(`${base}-${n}`)) n += 1;
  return `${base}-${n}`;
}

/** Slugify, falling back to a short id fragment when the name yields nothing. */
export function slugifyOrFallback(input: string, fallbackId: string): string {
  return slugify(input) || fallbackId.slice(0, 8);
}
