#!/usr/bin/env bun
/**
 * Parses src/routeTree.gen.ts and emits the registered-routes manifest with the
 * full list of registered route paths so the browser-side Route Health page and
 * command palette can verify advertised links without parsing the route tree.
 *
 * Two consumers import the manifest from different paths, so we write BOTH and
 * keep them byte-identical — otherwise they silently drift (see the ops legend
 * test that asserts every tile route is registered).
 *
 * Run: bun scripts/generate-route-manifest.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const TREE = join(ROOT, "src", "routeTree.gen.ts");
const OUTS = [
  join(ROOT, "src", "lib", "registered-routes.generated.ts"),
  join(ROOT, "src", "lib", "routing", "registered-routes.generated.ts"),
];

const src = readFileSync(TREE, "utf8");
const paths = new Set<string>();

for (const m of src.matchAll(/\bpath:\s*'([^']+)'/g)) paths.add(m[1]);
for (const m of src.matchAll(/'(\/[A-Za-z0-9_/$.\-]*)':\s*typeof/g)) paths.add(m[1]);
paths.add("/");

const sorted = [...paths].sort();
const body = `// AUTO-GENERATED by scripts/generate-route-manifest.ts — do not edit.
// Run \`bun scripts/generate-route-manifest.ts\` to refresh.
export const REGISTERED_ROUTES: readonly string[] = ${JSON.stringify(sorted, null, 2)} as const;
export const ROUTE_MANIFEST_GENERATED_AT = ${JSON.stringify(new Date().toISOString())};
`;
for (const out of OUTS) {
  writeFileSync(out, body);
  console.log(`✓ Wrote ${sorted.length} routes to ${out}`);
}
