-- Triggers
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER attendance_entries_updated_at BEFORE UPDATE ON public.attendance_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_mapping_presets_updated_at BEFORE UPDATE ON public.attendance_import_mapping_presets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_log_no_delete BEFORE DELETE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();
CREATE TRIGGER audit_log_no_update BEFORE UPDATE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();
CREATE TRIGGER trg_chat_messages_auto_unarchive AFTER INSERT ON public.chat_messages FOR EACH ROW EXECUTE FUNCTION auto_unarchive_chat_message();
CREATE TRIGGER trg_set_entity_slug BEFORE INSERT ON public.client_entities FOR EACH ROW EXECUTE FUNCTION set_entity_slug();
CREATE TRIGGER trg_clients_updated_at BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_hr_settings_updated_at BEFORE UPDATE ON public.company_hr_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_cea_updated BEFORE UPDATE ON public.connected_email_accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER contract_profiles_updated_at BEFORE UPDATE ON public.contract_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER contract_templates_updated_at BEFORE UPDATE ON public.contract_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_daily_note_template_updated_at BEFORE UPDATE ON public.daily_note_templates FOR EACH ROW EXECUTE FUNCTION _upd_daily_note_template_ts();
CREATE TRIGGER daily_notes_updated_at BEFORE UPDATE ON public.daily_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_direct_client_addresses_updated BEFORE UPDATE ON public.direct_client_addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_direct_client_contacts_updated BEFORE UPDATE ON public.direct_client_contacts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_dc_sharepoint_updated BEFORE UPDATE ON public.direct_client_sharepoint_config FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_dc_task_pricing_updated BEFORE UPDATE ON public.direct_client_task_pricing FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_direct_client_task_types_updated_at BEFORE UPDATE ON public.direct_client_task_types FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_direct_clients_assign_code BEFORE INSERT ON public.direct_clients FOR EACH ROW EXECUTE FUNCTION direct_clients_assign_code();
CREATE TRIGGER trg_direct_clients_updated_at BEFORE UPDATE ON public.direct_clients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_directclients_name_no_firm BEFORE INSERT OR UPDATE OF display_name ON public.direct_clients FOR EACH ROW EXECUTE FUNCTION enforce_firm_directclient_name_unique();
CREATE TRIGGER trg_document_backup AFTER INSERT ON public.document_nodes FOR EACH ROW EXECUTE FUNCTION _enqueue_document_backup();
CREATE TRIGGER trg_document_nodes_updated_at BEFORE UPDATE ON public.document_nodes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_documents_delete_sharepoint AFTER UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION enqueue_sharepoint_delete_file();
CREATE TRIGGER trg_ecl_recount AFTER INSERT OR DELETE ON public.email_context_links FOR EACH ROW EXECUTE FUNCTION email_context_links_recount();
CREATE TRIGGER trg_ecl_validate BEFORE INSERT OR UPDATE ON public.email_context_links FOR EACH ROW EXECUTE FUNCTION email_context_links_validate();
CREATE TRIGGER employee_audit_block_update BEFORE DELETE OR UPDATE ON public.employee_audit FOR EACH ROW EXECUTE FUNCTION employee_audit_block_mutation();
CREATE TRIGGER trg_entity_notes_updated BEFORE UPDATE ON public.entity_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER esign_audit_no_delete BEFORE DELETE ON public.esign_audit_log FOR EACH ROW EXECUTE FUNCTION esign_audit_block_mutation();
CREATE TRIGGER esign_audit_no_update BEFORE UPDATE ON public.esign_audit_log FOR EACH ROW EXECUTE FUNCTION esign_audit_block_mutation();
CREATE TRIGGER esign_envelopes_target_xor BEFORE INSERT OR UPDATE ON public.esign_envelopes FOR EACH ROW EXECUTE FUNCTION validate_esign_target_xor();
CREATE TRIGGER esign_envelopes_updated_at BEFORE UPDATE ON public.esign_envelopes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_firm_addresses_updated BEFORE UPDATE ON public.firm_addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.firm_contacts FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER trg_firm_contacts_updated BEFORE UPDATE ON public.firm_contacts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_firm_message_backup AFTER INSERT ON public.firm_messages FOR EACH ROW EXECUTE FUNCTION _enqueue_firm_message_backup();
CREATE TRIGGER trg_firm_sharepoint_config_updated_at BEFORE UPDATE ON public.firm_sharepoint_config FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.firms FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER firms_updated_at BEFORE UPDATE ON public.firms FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_firms_enqueue_sharepoint AFTER INSERT ON public.firms FOR EACH ROW EXECUTE FUNCTION enqueue_sharepoint_provision_firm();
CREATE TRIGGER trg_firms_name_no_directclient BEFORE INSERT OR UPDATE OF name ON public.firms FOR EACH ROW EXECUTE FUNCTION enforce_firm_directclient_name_unique();
CREATE TRIGGER trg_firms_normalize_identifier BEFORE INSERT OR UPDATE OF firm_identifier ON public.firms FOR EACH ROW EXECUTE FUNCTION firms_normalize_identifier();
CREATE TRIGGER trg_folder_library_templates_updated_at BEFORE UPDATE ON public.folder_library_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_idempotency_keys_audit AFTER INSERT OR DELETE OR UPDATE ON public.idempotency_keys FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER trg_incident_records_audit AFTER INSERT OR DELETE OR UPDATE ON public.incident_records FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER trg_incident_records_updated_at BEFORE UPDATE ON public.incident_records FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_integration_credentials_updated_at BEFORE UPDATE ON public.integration_credentials FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER leads_updated_at BEFORE UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_learning_answers_updated_at BEFORE UPDATE ON public.learning_answers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_learning_news_posts_updated_at BEFORE UPDATE ON public.learning_news_posts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_learning_questions_updated_at BEFORE UPDATE ON public.learning_questions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_leave_template_updated_at BEFORE UPDATE ON public.leave_policy_templates FOR EACH ROW EXECUTE FUNCTION _upd_leave_template_ts();
CREATE TRIGGER leave_requests_updated_at BEFORE UPDATE ON public.leave_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER marketing_assets_updated_at BEFORE UPDATE ON public.marketing_assets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER marketing_campaigns_updated_at BEFORE UPDATE ON public.marketing_campaigns FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_open_point_reply_answered AFTER INSERT ON public.open_point_replies FOR EACH ROW EXECUTE FUNCTION tg_open_point_reply_answered();
CREATE TRIGGER trg_organizer_block_scores_updated BEFORE UPDATE ON public.organizer_block_scores FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_organizer_blocks_updated BEFORE UPDATE ON public.organizer_blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_organizer_deployments_updated BEFORE UPDATE ON public.organizer_deployments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_organizer_submitted_link_task AFTER UPDATE OF status ON public.organizer_deployments FOR EACH ROW EXECUTE FUNCTION on_organizer_submitted_link_to_task();
CREATE TRIGGER trg_organizer_public_links_updated_at BEFORE UPDATE ON public.organizer_public_links FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_organizer_response_history AFTER INSERT OR UPDATE ON public.organizer_responses FOR EACH ROW EXECUTE FUNCTION log_organizer_response_change();
CREATE TRIGGER trg_organizer_responses_updated BEFORE UPDATE ON public.organizer_responses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_organizer_templates_updated BEFORE UPDATE ON public.organizer_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payroll_entries_updated_at BEFORE UPDATE ON public.payroll_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payroll_leave_policies_updated_at BEFORE UPDATE ON public.payroll_leave_policies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payroll_runs_updated_at BEFORE UPDATE ON public.payroll_runs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_payroll_salary_structures_updated_at BEFORE UPDATE ON public.payroll_salary_structures FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_pdf_template_fields_updated_at BEFORE UPDATE ON public.pdf_template_fields FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_pdf_templates_updated_at BEFORE UPDATE ON public.pdf_templates FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER personal_reminders_updated_at BEFORE UPDATE ON public.personal_reminders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER enforce_profile_self_update BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION enforce_profile_self_update();
CREATE TRIGGER profiles_prevent_cycle BEFORE INSERT OR UPDATE OF reports_to ON public.profiles FOR EACH ROW EXECUTE FUNCTION prevent_reporting_cycle();
CREATE TRIGGER trg_pdiff_updated_at BEFORE UPDATE ON public.project_difficulty_levels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_pft_updated_at BEFORE UPDATE ON public.project_feature_toggles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_project_file_categories_updated_at BEFORE UPDATE ON public.project_file_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_project_file_tags_updated BEFORE UPDATE ON public.project_file_tags FOR EACH ROW EXECUTE FUNCTION touch_project_file_tags_updated_at();
CREATE TRIGGER trg_fixed_model_guard BEFORE INSERT OR UPDATE ON public.project_pricing_fixed_assignments FOR EACH ROW EXECUTE FUNCTION enforce_pricing_child_model();
CREATE TRIGGER trg_fixed_updated BEFORE UPDATE ON public.project_pricing_fixed_assignments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_matrix_model_guard BEFORE INSERT OR UPDATE ON public.project_pricing_matrix_rates FOR EACH ROW EXECUTE FUNCTION enforce_pricing_child_model();
CREATE TRIGGER trg_matrix_updated BEFORE UPDATE ON public.project_pricing_matrix_rates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_pricing_period_currency BEFORE INSERT ON public.project_pricing_periods FOR EACH ROW EXECUTE FUNCTION set_pricing_period_currency();
CREATE TRIGGER trg_pricing_period_updated BEFORE UPDATE ON public.project_pricing_periods FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_project_pricing_rules_updated_at BEFORE UPDATE ON public.project_pricing_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_prt_updated_at BEFORE UPDATE ON public.project_return_types FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER project_task_options_updated_at BEFORE UPDATE ON public.project_task_options FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_purg_updated_at BEFORE UPDATE ON public.project_urgency_levels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER projects_seed_pipeline AFTER INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION seed_default_pipeline_stages();
CREATE TRIGGER projects_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_projects_enqueue_sharepoint AFTER INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION enqueue_sharepoint_create_project_folder();
CREATE TRIGGER trg_provision_project_lists AFTER UPDATE ON public.projects FOR EACH ROW WHEN (((old.sharepoint_site_id IS NULL) AND (new.sharepoint_site_id IS NOT NULL))) EXECUTE FUNCTION _enqueue_provision_project_lists();
CREATE TRIGGER trg_seed_default_pipeline_stages AFTER INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION seed_default_pipeline_stages();
CREATE TRIGGER trg_seed_project_setup AFTER INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION seed_default_project_setup();
CREATE TRIGGER trg_set_project_slug BEFORE INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION set_project_slug();
CREATE TRIGGER trg_restore_drill_log_audit AFTER INSERT OR DELETE OR UPDATE ON public.restore_drill_log FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER trg_enforce_subrole_capability_ceiling BEFORE INSERT OR UPDATE ON public.role_subrole_capabilities FOR EACH ROW EXECUTE FUNCTION enforce_subrole_capability_ceiling();
CREATE TRIGGER trg_role_subroles_updated_at BEFORE UPDATE ON public.role_subroles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER sal_no_delete BEFORE DELETE ON public.sensitive_action_log FOR EACH ROW EXECUTE FUNCTION sal_block_mutation();
CREATE TRIGGER sal_no_update BEFORE UPDATE ON public.sensitive_action_log FOR EACH ROW EXECUTE FUNCTION sal_block_mutation();
CREATE TRIGGER trg_sharepoint_sync_jobs_updated_at BEFORE UPDATE ON public.sharepoint_sync_jobs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sharepoint_upload_sessions_updated_at BEFORE UPDATE ON public.sharepoint_upload_sessions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_sops_updated BEFORE UPDATE ON public.sops FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_staff_compensation_updated BEFORE UPDATE ON public.staff_compensation FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.task_action_items FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER task_action_items_edit_window BEFORE UPDATE ON public.task_action_items FOR EACH ROW EXECUTE FUNCTION enforce_30min_edit_window();
CREATE TRIGGER trg_task_action_items_audit AFTER INSERT OR UPDATE ON public.task_action_items FOR EACH ROW EXECUTE FUNCTION task_action_items_audit();
CREATE TRIGGER trg_task_action_items_bi BEFORE INSERT ON public.task_action_items FOR EACH ROW EXECUTE FUNCTION task_action_items_before_ins();
CREATE TRIGGER trg_task_action_items_bu BEFORE UPDATE ON public.task_action_items FOR EACH ROW EXECUTE FUNCTION task_action_items_before_upd();
CREATE TRIGGER task_attachments_audit_doc AFTER INSERT OR UPDATE ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION trg_audit_task_attachments();
CREATE TRIGGER task_attachments_resolve_visibility BEFORE INSERT OR UPDATE OF client_visible_override, folder_path ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION trg_attachment_resolve_visibility();
CREATE TRIGGER trg_task_attachment_sp_sync AFTER INSERT ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION _enqueue_migrate_attachment();
CREATE TRIGGER trg_audit_backup AFTER INSERT ON public.task_audit FOR EACH ROW EXECUTE FUNCTION _enqueue_audit_backup();
CREATE TRIGGER trg_billable_event_lock BEFORE UPDATE ON public.task_billable_events FOR EACH ROW EXECUTE FUNCTION enforce_billable_event_immutability();
CREATE TRIGGER trg_event_recall_voids_invoice AFTER UPDATE OF status ON public.task_billable_events FOR EACH ROW EXECUTE FUNCTION on_event_recalled_void_invoice();
CREATE TRIGGER trg_events_updated BEFORE UPDATE ON public.task_billable_events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER task_document_folders_audit AFTER INSERT OR DELETE OR UPDATE ON public.task_document_folders FOR EACH ROW EXECUTE FUNCTION trg_audit_task_document_folders();
CREATE TRIGGER task_document_folders_visibility_refresh AFTER UPDATE ON public.task_document_folders FOR EACH ROW EXECUTE FUNCTION trg_folder_visibility_changed();
CREATE TRIGGER trg_tfa_updated_at BEFORE UPDATE ON public.task_file_annotations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_task_folder_metadata_updated_at BEFORE UPDATE ON public.task_folder_metadata FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER task_links_edit_window BEFORE UPDATE ON public.task_links FOR EACH ROW EXECUTE FUNCTION enforce_30min_edit_window();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.task_messages FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER enforce_task_message_edit_policy_trg BEFORE UPDATE ON public.task_messages FOR EACH ROW EXECUTE FUNCTION enforce_task_message_edit_policy();
CREATE TRIGGER task_message_audit_on_visibility AFTER UPDATE ON public.task_messages FOR EACH ROW EXECUTE FUNCTION task_message_audit_trigger();
CREATE TRIGGER trg_task_message_backup AFTER INSERT ON public.task_messages FOR EACH ROW EXECUTE FUNCTION _enqueue_task_message_backup();
CREATE TRIGGER trg_task_messages_auto_unarchive AFTER INSERT ON public.task_messages FOR EACH ROW EXECUTE FUNCTION auto_unarchive_task_message();
CREATE TRIGGER trg_task_messages_email_notify AFTER INSERT ON public.task_messages FOR EACH ROW EXECUTE FUNCTION _queue_task_email_on_message();
CREATE TRIGGER trg_task_messages_whatsapp_notify AFTER INSERT ON public.task_messages FOR EACH ROW EXECUTE FUNCTION _queue_task_whatsapp_on_message();
CREATE TRIGGER trg_task_my_day_audit AFTER INSERT OR UPDATE ON public.task_my_day FOR EACH ROW EXECUTE FUNCTION task_my_day_audit();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.task_notes FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER task_notes_edit_window BEFORE UPDATE ON public.task_notes FOR EACH ROW EXECUTE FUNCTION enforce_30min_edit_window();
CREATE TRIGGER trg_task_notes_updated BEFORE UPDATE ON public.task_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_task_permissions_updated BEFORE UPDATE ON public.task_permissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_stage_completion_to_ledger AFTER INSERT ON public.task_stage_completions FOR EACH ROW EXECUTE FUNCTION on_stage_completion_to_ledger();
CREATE TRIGGER task_subtasks_default_sort_before BEFORE INSERT ON public.task_subtasks FOR EACH ROW EXECUTE FUNCTION trg_task_subtasks_default_sort();
CREATE TRIGGER task_subtasks_normalize_after AFTER INSERT OR DELETE OR UPDATE ON public.task_subtasks FOR EACH ROW EXECUTE FUNCTION trg_task_subtasks_normalize();
CREATE TRIGGER trg_subtask_sync_status BEFORE INSERT OR UPDATE ON public.task_subtasks FOR EACH ROW EXECUTE FUNCTION sync_subtask_status_done();
CREATE TRIGGER trg_task_subtasks_audit AFTER INSERT OR DELETE OR UPDATE ON public.task_subtasks FOR EACH ROW EXECUTE FUNCTION task_subtasks_audit();
CREATE TRIGGER task_views_set_updated_at BEFORE UPDATE ON public.task_views FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER task_audit_on_tasks AFTER INSERT OR UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION task_audit_trigger();
CREATE TRIGGER tasks_audit_trigger AFTER INSERT OR UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION task_audit_trigger();
CREATE TRIGGER tasks_default_stage BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION default_task_pipeline_stage();
CREATE TRIGGER trg_assign_task_display_id BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION assign_task_display_id();
CREATE TRIGGER trg_set_task_slug BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION set_task_slug();
CREATE TRIGGER trg_task_backup_insert AFTER INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION _enqueue_task_backup();
CREATE TRIGGER trg_task_backup_update AFTER UPDATE ON public.tasks FOR EACH ROW WHEN (((old.status IS DISTINCT FROM new.status) OR (old.priority IS DISTINCT FROM new.priority) OR (old.complexity IS DISTINCT FROM new.complexity) OR (old.due_date IS DISTINCT FROM new.due_date) OR (old.title IS DISTINCT FROM new.title))) EXECUTE FUNCTION _enqueue_task_backup();
CREATE TRIGGER trg_task_unsorted_folder AFTER INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION create_unsorted_documents_folder();
CREATE TRIGGER trg_tasks_archive_sharepoint BEFORE DELETE ON public.tasks FOR EACH ROW EXECUTE FUNCTION enqueue_sharepoint_archive_task_folder();
CREATE TRIGGER trg_tasks_email_notify AFTER UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION _queue_task_email_on_update();
CREATE TRIGGER trg_tasks_enqueue_sharepoint AFTER INSERT ON public.tasks FOR EACH ROW WHEN ((new.stream = 'cpa'::text)) EXECUTE FUNCTION enqueue_sharepoint_create_task_folder();
CREATE TRIGGER trg_tasks_patch_metadata_sharepoint AFTER UPDATE ON public.tasks FOR EACH ROW WHEN ((new.stream = 'cpa'::text)) EXECUTE FUNCTION enqueue_sharepoint_patch_task_metadata();
CREATE TRIGGER trg_tasks_rename_sharepoint AFTER UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION enqueue_sharepoint_rename_task_folder();
CREATE TRIGGER trg_tasks_whatsapp_notify AFTER UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION _queue_task_whatsapp_on_update();
CREATE TRIGGER trg_enforce_single_open_timer BEFORE INSERT OR UPDATE ON public.time_logs FOR EACH ROW EXECUTE FUNCTION enforce_single_open_timer();
CREATE TRIGGER trg_stamp_effective_editor BEFORE UPDATE ON public.time_logs FOR EACH ROW EXECUTE FUNCTION stamp_effective_editor();
CREATE TRIGGER trg_time_log_to_ledger AFTER INSERT OR UPDATE OF ended_at, effective_override, duration_minutes, break_minutes, billable ON public.time_logs FOR EACH ROW EXECUTE FUNCTION on_time_log_to_ledger();
CREATE TRIGGER trg_time_logs_audit AFTER INSERT OR UPDATE ON public.time_logs FOR EACH ROW EXECUTE FUNCTION fn_time_logs_audit();
CREATE TRIGGER trg_tet_updated BEFORE UPDATE ON public.tracked_email_threads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER training_assignments_updated_at BEFORE UPDATE ON public.training_assignments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER training_courses_updated_at BEFORE UPDATE ON public.training_courses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_training_notes_updated_at BEFORE UPDATE ON public.training_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_training_paths_updated_at BEFORE UPDATE ON public.training_paths FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_client_prefs_updated_at BEFORE UPDATE ON public.user_client_prefs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_user_otp_channels_updated_at BEFORE UPDATE ON public.user_otp_channels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER audit_changes AFTER INSERT OR DELETE OR UPDATE ON public.user_roles FOR EACH ROW EXECUTE FUNCTION audit_row_changes();
CREATE TRIGGER trg_user_ui_prefs_updated_at BEFORE UPDATE ON public.user_ui_prefs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
