#!/usr/bin/env python3
"""
assemble_01_public.py
Builds supabase/_baseline/01_public.sql from section files + MCP temp files.
Run from repo root: python supabase/_baseline/assemble_01_public.py
"""

import json
import os
import re
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
BASELINE = Path(__file__).parent
SECTIONS = BASELINE / "sections"
OUT = BASELINE / "01_public.sql"

TMPDIR = Path(r"C:\Users\Avani\.claude\projects\Z--Application-Development-BusAcTa-Operations\63cad558-c32c-4cca-bd34-6988d3371b8a\tool-results")

TEMP_FILES = {
    "tables":      TMPDIR / "mcp-supabase-execute_sql-1782023322280.txt",
    "constraints": TMPDIR / "mcp-supabase-execute_sql-1782022852489.txt",
    "indexes":     TMPDIR / "toolu_01Eb45BZz3YEpN9KJBbuyv1M.json",
    "functions":   TMPDIR / "mcp-supabase-execute_sql-1782023134017.txt",
    "grants":      TMPDIR / "mcp-supabase-execute_sql-1782023136784.txt",
    "policies":    TMPDIR / "mcp-supabase-execute_sql-1782023231791.txt",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

UNTRUSTED_RE = re.compile(
    # tags on their own lines (skip the inline "below <tag> boundaries" mention)
    r'\n<untrusted-data-[a-f0-9-]+>\n(.*?)\n</untrusted-data-[a-f0-9-]+>',
    re.DOTALL
)


def _find_array_in_text(text: str) -> list | None:
    """Find and parse the JSON array inside block-level <untrusted-data-...> tags."""
    m = UNTRUSTED_RE.search(text)
    if m:
        inner = m.group(1).strip()
        if inner:
            return json.loads(inner)
    return None


def extract_json_array(text: str) -> list:
    """Extract the JSON rows array from an MCP tool-result file (multiple formats).

    Files are stored in one of:
      A. Outer JSON: {"result": "...text with <untrusted-data> tags..."} — most .txt files
      B. Plain text: raw text with <untrusted-data> tags (no outer JSON wrapper)
      C. [{"type":"text","text":"..."}] — some .json files
    """
    # Always try outer-JSON parse first so escape sequences are resolved before regex
    try:
        outer = json.loads(text)

        # Format A: {"result": "..."}
        if isinstance(outer, dict) and "result" in outer:
            result = _find_array_in_text(outer["result"])
            if result is not None:
                return result

        # Format C: [{"type":"text","text":"..."}]
        if isinstance(outer, list) and outer and isinstance(outer[0], dict):
            inner_text = outer[0].get("text", "")
            # inner_text may itself be {"result": "..."}
            try:
                inner_obj = json.loads(inner_text)
                if isinstance(inner_obj, dict) and "result" in inner_obj:
                    inner_text = inner_obj["result"]
            except (json.JSONDecodeError, TypeError):
                pass
            result = _find_array_in_text(inner_text)
            if result is not None:
                return result
            # Already a DDL array?
            if outer[0].get("ddl"):
                return outer

        # Format: outer JSON is itself the array
        if isinstance(outer, list) and outer and isinstance(outer[0], dict) and "ddl" in outer[0]:
            return outer

    except (json.JSONDecodeError, TypeError):
        pass

    # Format B: plain text (no outer JSON wrapper) — try regex directly
    result = _find_array_in_text(text)
    if result is not None:
        return result

    raise ValueError(f"Could not parse MCP result (first 200 chars): {text[:200]!r}")


def extract_ddl(label: str, filepath: Path) -> str:
    """Read a temp file and return concatenated DDL strings."""
    if not filepath.exists():
        sys.exit(f"ERROR: Temp file not found: {filepath}")
    content = filepath.read_text(encoding="utf-8", errors="replace")
    rows = extract_json_array(content)
    parts = [str(r["ddl"]) for r in rows if r.get("ddl")]
    result = "\n".join(parts)
    print(f"  {label:20s}  {len(rows):4d} rows  {len(result):>9,} chars")
    return result


def read_section(filename: str) -> str:
    p = SECTIONS / filename
    if not p.exists():
        sys.exit(f"ERROR: Section file not found: {p}")
    text = p.read_text(encoding="utf-8").strip()
    print(f"  {filename:30s}  {len(text):>9,} chars")
    return text


# ── Assemble ──────────────────────────────────────────────────────────────────

blocks: list[str] = [
    "-- ============================================================",
    "-- 01 · Public schema",
    "-- Generated by assemble_01_public.py from MCP catalog queries",
    "-- Sections:",
    "--   1. Enum types       (72 types)",
    "--   2. Sequences        (4 sequences)",
    "--   3. Tables           (216 tables, columns + defaults)",
    "--   4. Constraints      (PK, UNIQUE, CHECK, FK)",
    "--   5. Indexes          (non-constraint-backed)",
    "--   6. Functions        (358 functions/procedures)",
    "--   7. Triggers",
    "--   8. RLS enable",
    "--   9. RLS policies     (487 policies)",
    "--  10. Grants           (anon/authenticated/service_role)",
    "-- ============================================================",
    "",
]


def add_section(header: str, ddl: str):
    sep = "-" * max(1, 60 - len(header))
    blocks.append(f"-- -- {header} {sep}")
    blocks.append("")
    blocks.append(ddl)
    blocks.append("")


print("=" * 60)
print("Building supabase/_baseline/01_public.sql")
print("=" * 60)

print("\nSection files:")
add_section("Enum types",  read_section("s01_enums.sql"))
add_section("Sequences",   read_section("s02_sequences.sql"))

print("\nTemp files (MCP catalog queries):")
add_section("Tables",      extract_ddl("tables",      TEMP_FILES["tables"]))
add_section("Constraints", extract_ddl("constraints", TEMP_FILES["constraints"]))
add_section("Indexes",     extract_ddl("indexes",     TEMP_FILES["indexes"]))
add_section("Functions",   extract_ddl("functions",   TEMP_FILES["functions"]))

print("\nSection files:")
add_section("Triggers",    read_section("s07_triggers.sql"))
add_section("RLS enable",  read_section("s08_rls_enable.sql"))

print("\nTemp files (MCP catalog queries):")
add_section("Policies",    extract_ddl("policies", TEMP_FILES["policies"]))
add_section("Grants",      extract_ddl("grants",   TEMP_FILES["grants"]))

sql = "\n".join(blocks)
OUT.write_text(sql, encoding="utf-8")

kb = len(sql) / 1024
print(f"\nDone! Written {OUT}")
print(f"   Size: {kb:.0f} KB ({len(sql):,} chars)")
