/**
 * generate_schema.ts
 * Run: bun run supabase/_baseline/generate_schema.ts
 *
 * Queries the live Supabase Postgres DB and writes the full public-schema DDL
 * to supabase/_baseline/01_public.sql, ready for the assemble.ps1 step.
 *
 * Requires DATABASE_URL in .env (postgres://... format).
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import pg from "pg";

const { Pool } = pg;

// ── env ──────────────────────────────────────────────────────────────────────
const envPath = resolve(process.cwd(), ".env");
const envContent = readFileSync(envPath, "utf8");
const dbUrlMatch = envContent.match(/^DATABASE_URL="?([^"\n]+)"?/m);
if (!dbUrlMatch) throw new Error("DATABASE_URL not found in .env");
const DATABASE_URL = dbUrlMatch[1];

const pool = new Pool({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } });

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "01_public.sql");

const lines: string[] = [
  "-- ============================================================",
  "-- 01 · Public schema",
  "-- Generated by supabase/_baseline/generate_schema.ts",
  "-- Sections: enums → sequences → tables → constraints → indexes",
  "--            → functions → triggers → RLS → policies → grants",
  "-- ============================================================",
  "",
];

function emit(...stmts: string[]) {
  for (const s of stmts) lines.push(s);
}

async function query(sql: string): Promise<Record<string, unknown>[]> {
  const client = await pool.connect();
  try {
    const res = await client.query(sql);
    return res.rows;
  } finally {
    client.release();
  }
}

// ── 1. ENUM TYPES ─────────────────────────────────────────────────────────────
console.log("Fetching enums…");
emit("-- ── Enum types ──────────────────────────────────────────────────────────");
const enums = await query(`
  SELECT t.typname,
    string_agg(quote_literal(e.enumlabel), E',\n  ' ORDER BY e.enumsortorder) AS labels
  FROM pg_type t
  JOIN pg_namespace n ON n.oid = t.typnamespace
  JOIN pg_enum e ON e.enumtypid = t.oid
  WHERE n.nspname = 'public'
  GROUP BY t.typname
  ORDER BY t.typname
`);
for (const r of enums) {
  emit(`CREATE TYPE public.${r.typname} AS ENUM (\n  ${r.labels}\n);`);
}
emit("");

// ── 2. SEQUENCES ──────────────────────────────────────────────────────────────
console.log("Fetching sequences…");
emit("-- ── Sequences ────────────────────────────────────────────────────────────");
const seqs = await query(`
  SELECT s.relname,
    p.start_value, p.minimum_value, p.maximum_value, p.increment, p.cycle_option
  FROM pg_class s
  JOIN pg_namespace n ON n.oid = s.relnamespace
  JOIN information_schema.sequences p
    ON p.sequence_name = s.relname AND p.sequence_schema = 'public'
  WHERE n.nspname = 'public' AND s.relkind = 'S'
    AND NOT EXISTS (
      SELECT 1 FROM pg_depend d
      WHERE d.objid = s.oid AND d.deptype = 'a'
    )
  ORDER BY s.relname
`);
for (const r of seqs) {
  emit(
    `CREATE SEQUENCE IF NOT EXISTS public.${r.relname}` +
      ` START WITH ${r.start_value}` +
      ` INCREMENT BY ${r.increment}` +
      ` MINVALUE ${r.minimum_value}` +
      ` MAXVALUE ${r.maximum_value}` +
      (r.cycle_option === "YES" ? " CYCLE" : " NO CYCLE") +
      ";",
  );
}
emit("");

// ── 3. TABLES ─────────────────────────────────────────────────────────────────
console.log("Fetching tables…");
emit("-- ── Tables ────────────────────────────────────────────────────────────────");
const tables = await query(`
  SELECT t.relname AS tbl,
    string_agg(
      '  ' || quote_ident(a.attname) || ' ' ||
      pg_catalog.format_type(a.atttypid, a.atttypmod) ||
      CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END ||
      CASE WHEN a.atthasdef THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid) ELSE '' END,
      E',\n' ORDER BY a.attnum
    ) AS cols
  FROM pg_class t
  JOIN pg_namespace n ON n.oid = t.relnamespace
  JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped
  LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
  WHERE n.nspname = 'public' AND t.relkind = 'r'
  GROUP BY t.relname
  ORDER BY t.relname
`);
for (const r of tables) {
  emit(`CREATE TABLE IF NOT EXISTS public.${r.tbl} (\n${r.cols}\n);`);
}
emit("");

// ── 4. CONSTRAINTS (PK, UNIQUE, CHECK, FK) ────────────────────────────────────
console.log("Fetching constraints…");
emit("-- ── Constraints ───────────────────────────────────────────────────────────");
const constraints = await query(`
  SELECT
    'ALTER TABLE public.' || quote_ident(t.relname) ||
    ' ADD CONSTRAINT ' || quote_ident(c.conname) ||
    ' ' || pg_get_constraintdef(c.oid, true) || ';' AS ddl,
    CASE c.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'f' THEN 4 END AS sort_order
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public' AND c.contype IN ('p','u','c','f')
  ORDER BY sort_order, t.relname, c.conname
`);
for (const r of constraints) emit(String(r.ddl));
emit("");

// ── 5. INDEXES (non-pk, non-constraint-backed) ────────────────────────────────
console.log("Fetching indexes…");
emit("-- ── Indexes ────────────────────────────────────────────────────────────────");
const indexes = await query(`
  SELECT pg_get_indexdef(i.indexrelid) || ';' AS ddl
  FROM pg_index i
  JOIN pg_class t ON t.oid = i.indrelid
  JOIN pg_class ix ON ix.oid = i.indexrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public'
    AND NOT i.indisprimary
    AND NOT EXISTS (
      SELECT 1 FROM pg_constraint c
      WHERE c.conindid = i.indexrelid AND c.contype IN ('u','p')
    )
  ORDER BY t.relname, ix.relname
`);
for (const r of indexes) emit(String(r.ddl));
emit("");

// ── 6. FUNCTIONS & PROCEDURES ─────────────────────────────────────────────────
console.log("Fetching functions…");
emit("-- ── Functions ──────────────────────────────────────────────────────────────");
const funcs = await query(`
  SELECT pg_get_functiondef(p.oid) || ';' AS ddl
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public'
    AND p.prokind IN ('f','p')
  ORDER BY p.proname, p.oid
`);
for (const r of funcs) emit(String(r.ddl));
emit("");

// ── 7. TRIGGERS ───────────────────────────────────────────────────────────────
console.log("Fetching triggers…");
emit("-- ── Triggers ───────────────────────────────────────────────────────────────");
const triggers = await query(`
  SELECT pg_get_triggerdef(t.oid) || ';' AS ddl
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND NOT t.tgisinternal
  ORDER BY c.relname, t.tgname
`);
for (const r of triggers) emit(String(r.ddl));
emit("");

// ── 8. RLS ENABLE ─────────────────────────────────────────────────────────────
console.log("Fetching RLS enable statements…");
emit("-- ── Row Level Security ─────────────────────────────────────────────────────");
const rlsTables = await query(`
  SELECT relname
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
  ORDER BY relname
`);
for (const r of rlsTables) {
  emit(`ALTER TABLE public.${r.relname} ENABLE ROW LEVEL SECURITY;`);
}
emit("");

// ── 9. RLS POLICIES ───────────────────────────────────────────────────────────
console.log("Fetching RLS policies…");
emit("-- ── Policies ───────────────────────────────────────────────────────────────");
const policies = await query(`
  SELECT tablename, policyname, permissive, roles, cmd, qual, with_check
  FROM pg_policies
  WHERE schemaname = 'public'
  ORDER BY tablename, policyname
`);
for (const r of policies) {
  const tbl = `public.${r.tablename}`;
  const perm = r.permissive === "PERMISSIVE" ? "PERMISSIVE" : "RESTRICTIVE";
  const roles = (r.roles as string).replace(/^\{|\}$/g, "");
  const toClause = roles && roles !== "public" ? ` TO ${roles}` : "";
  const usingClause = r.qual ? ` USING (${r.qual})` : "";
  const checkClause = r.with_check ? ` WITH CHECK (${r.with_check})` : "";
  emit(
    `DROP POLICY IF EXISTS ${JSON.stringify(r.policyname)} ON ${tbl};`,
    `CREATE POLICY ${JSON.stringify(r.policyname)} ON ${tbl} AS ${perm}` +
      ` FOR ${r.cmd}${toClause}${usingClause}${checkClause};`,
  );
}
emit("");

// ── 10. GRANTS ────────────────────────────────────────────────────────────────
console.log("Fetching grants…");
emit("-- ── Grants ─────────────────────────────────────────────────────────────────");
const grants = await query(`
  SELECT
    'GRANT ' || privilege_type || ' ON public.' || quote_ident(table_name) ||
    ' TO ' || quote_ident(grantee) || ';' AS ddl
  FROM information_schema.role_table_grants
  WHERE table_schema = 'public'
    AND grantee IN ('anon','authenticated','service_role')
    AND grantor = 'postgres'
  ORDER BY table_name, grantee, privilege_type
`);
for (const r of grants) emit(String(r.ddl));

const seqGrants = await query(`
  SELECT
    'GRANT ' || p.privilege_type || ' ON SEQUENCE public.' || quote_ident(s.relname) ||
    ' TO ' || quote_ident(p.grantee::text) || ';' AS ddl
  FROM pg_class s
  JOIN pg_namespace n ON n.oid = s.relnamespace,
  aclexplode(s.relacl) AS p(grantor, grantee, privilege_type, is_grantable)
  WHERE n.nspname = 'public' AND s.relkind = 'S'
    AND p.grantee::text IN ('anon','authenticated','service_role')
  ORDER BY s.relname, p.grantee, p.privilege_type
`);
for (const r of seqGrants) emit(String(r.ddl));
emit("");

// ── write file ────────────────────────────────────────────────────────────────
await pool.end();
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`\n✓ Written to ${OUT} (${(lines.join("\n").length / 1024).toFixed(0)} KB)`);
